version: "3"
services:
  api:
    build: .
    image: institute
    ports:
      - "8080:8080"
  ui:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - C:\Users\TRA0004\Documents\Front End Area\Institute-Management:/usr/share/nginx/html
    depends_on:
      - api